[pytest]
# 如果不加asyncio的话，需要在每个def开头显式写入@pytest.mark.asyncio装饰器，否则会静默跳过，不执行
asyncio_mode = auto
# 限定test的收集范围，不写的话就会全局扫描，将venv中的引用库的测试文件也给测试了，测试更耗时，但无用
testpaths = tests
# 压低噪音，不让pydantic库的warning影响我们的输出质量
filterwarnings = ignore::UserWarning:pydantic.*
